//! Workflow definitions for CI/CD

use std::process::Command;

use crate::workflow_model::Workflow as PrivateWorkflow;

const GENERATED_HEADER: &str = "# -------------------------------------------------------------------\n# ------------------------------- WARNING ---------------------------\n#\n# This file is generated by forge_ci. Update the private workflow model\n# and regenerate; direct edits will be overwritten.\n#\n# -------------------------------------------------------------------\n# ----------------------------- END WARNING -------------------------\n# -------------------------------------------------------------------";

pub(crate) fn generate_private_workflow(workflow: PrivateWorkflow, name: &str) {
    let workflow_yaml = workflow.to_yaml().expect("workflow yaml");
    write_workflow(name, &workflow_yaml, "", false, true);
}

fn write_workflow(
    name: &str,
    workflow_yaml: &str,
    suffix: &str,
    normalize_generated_yaml: bool,
    require_byte_parity: bool,
) {
    let root = String::from_utf8(
        Command::new("git")
            .args(["rev-parse", "--show-toplevel"])
            .output()
            .expect("git root")
            .stdout,
    )
    .expect("git root utf8");
    let path = std::path::PathBuf::from(root.trim())
        .join(".github/workflows")
        .join(name);
    let workflow_yaml = if normalize_generated_yaml {
        workflow_yaml.replace(": \n", ":\n")
    } else {
        workflow_yaml.to_string()
    };
    let content = format!("{}\n{}{}", GENERATED_HEADER, workflow_yaml, suffix,);
    let current = std::fs::read_to_string(&path).ok();
    let equivalent = current.as_deref().is_some_and(|existing| {
        existing == content
            || match (
                serde_yaml_ng::from_str::<serde_yaml_ng::Value>(existing),
                serde_yaml_ng::from_str::<serde_yaml_ng::Value>(&content),
            ) {
                (Ok(left), Ok(right)) => left == right,
                _ => false,
            }
    });
    if std::env::var_os("CI").is_some() {
        assert!(
            equivalent,
            "generated workflow is stale: {}",
            path.display()
        );
    } else if normalize_generated_yaml && current.as_deref() != Some(content.as_str())
        || require_byte_parity && current.as_deref() != Some(content.as_str())
        || !normalize_generated_yaml && !require_byte_parity && !equivalent
    {
        std::fs::write(&path, content).expect("write workflow");
    }
}

mod autofix;
mod bounty;
mod ci;
mod labels;
mod release_drafter;
mod release_publish;
mod stale;

pub use autofix::*;
pub use bounty::*;
pub use ci::*;
pub use labels::*;
pub use release_drafter::*;
pub use release_publish::*;
pub use stale::*;
