# Forge: _forge_action_keyboard - Show keyboard shortcuts
function _forge_action_keyboard
    echo
    echo "Forge Fish Shell Plugin - Commands Reference"
    echo ""
    echo "  Keybindings"
    echo "  ───────────────────────────────────────────────────"
    echo "  Enter           Execute :command or send prompt to forge"
    echo "  Tab             Complete @file or :command with fzf"
    echo ""
    echo "  Prompts"
    echo "  ───────────────────────────────────────────────────"
    echo "  : <text>        Send prompt to forge (current conversation)"
    echo "  :new / :n       Start a new conversation"
    echo "  :edit / :ed     Open editor for multi-line prompt"
    echo "  :suggest / :s   Generate shell command from description"
    echo "  :retry / :r     Retry the last command"
    echo ""
    echo "  Conversations"
    echo "  ───────────────────────────────────────────────────"
    echo "  :conversation / :c    Switch between conversations"
    echo "  :rename / :rn         Rename current conversation"
    echo "  :conversation-rename  Rename a conversation by ID"
    echo "  :clone                Clone conversation context"
    echo "  :copy                 Copy last response to clipboard"
    echo "  :compact              Compact the conversation context"
    echo "  :dump / :d            Save conversation as JSON or HTML"
    echo ""
    echo "  Models & Providers"
    echo "  ───────────────────────────────────────────────────"
    echo "  :model / :m           Switch model (session only)"
    echo "  :config-model / :cm   Switch model (global config)"
    echo "  :config-provider / :p Switch provider (global config)"
    echo "  :reasoning-effort / :re  Set reasoning effort (session)"
    echo "  :config-reasoning-effort / :cre  Set reasoning effort (global)"
    echo "  :config-commit-model / :ccm      Set commit model"
    echo "  :config-suggest-model / :csm     Set suggest model"
    echo "  :config-reload / :cr  Reset all session overrides"
    echo ""
    echo "  Agents"
    echo "  ───────────────────────────────────────────────────"
    echo "  :agent / :a     Switch agent"
    echo "  :forge          Technical development agent"
    echo "  :sage           Research and analysis agent"
    echo "  :muse / :plan   Planning and strategy agent"
    echo ""
    echo "  Git"
    echo "  ───────────────────────────────────────────────────"
    echo "  :commit         Commit with AI-generated message"
    echo "  :commit-preview Preview AI-generated commit message"
    echo ""
    echo "  Workspace"
    echo "  ───────────────────────────────────────────────────"
    echo "  :workspace-sync / :sync   Sync workspace for search"
    echo "  :workspace-init           Initialize new workspace"
    echo "  :workspace-status         Show sync status"
    echo "  :workspace-info           Show workspace details"
    echo ""
    echo "  Info & Config"
    echo "  ───────────────────────────────────────────────────"
    echo "  :info / :i            Show session information"
    echo "  :env / :e             Show environment information"
    echo "  :config               Show configuration values"
    echo "  :config-edit / :ce    Edit global config file"
    echo "  :tools / :t           List available tools"
    echo "  :skill                List available skills"
    echo "  :doctor               Run environment diagnostics"
    echo "  :kb                   Show this reference"
    echo ""
    echo "  Auth"
    echo "  ───────────────────────────────────────────────────"
    echo "  :login                Login to a provider"
    echo "  :logout               Logout from a provider"
    echo ""
end
