//! # forge_sandbox
//!
//! Sandboxed code execution for the HeliosLite AI coding agent.
//!
//! Provides OS-level process isolation for running untrusted code generated by
//! the agent. Backends are platform-specific:
//!
//! | Platform | Mechanism                                    | Privilege |
//! |----------|----------------------------------------------|-----------|
//! | Linux    | Landlock (kernel 5.13+) — fs + net rules      | Unprivileged |
//! | macOS    | Seatbelt (`sandbox-exec`) — policy profiles  | Unprivileged |
//! | Windows  | Job objects + restricted token (placeholder)  | Medium    |
//!
//! ## Why
//!
//! AI coding agents routinely execute code they generate. Without isolation:
//!
//! - A prompt injection or hallucinated `rm -rf ~` will execute.
//! - Generated code can leak `~/.ssh/id_rsa` or `~/.aws/credentials`.
//! - A bug in `cargo test` invocation can corrupt the user's source tree.
//!
//! `forge_sandbox` wraps every tool execution in a sandboxed subprocess. The
//! sandbox is enforced by the kernel, not by the agent runtime, so a
//! confused/buggy agent cannot break out.
//!
//! ## Design
//!
//! ```text
//!     ┌───────────────────────────────┐
//!     │  HeliosLite agent             │
//!     │  (forge_infra / forge_app)    │
//!     └──────────────┬────────────────┘
//!                    │ Sandbox::exec()
//!                    ▼
//!     ┌───────────────────────────────┐
//!     │  forge_sandbox::Sandbox       │  ◀── trait-based
//!     └──────────────┬────────────────┘
//!                    │
//!         ┌──────────┼──────────┬──────────────┐
//!         ▼          ▼          ▼              ▼
//!      Linux     macOS      Windows        Disabled
//!      Landlock  Seatbelt   JobObject       (passthrough)
//! ```
//!
//! Each backend implements [`Backend`] and is chosen by [`Sandbox::for_platform`].
//! The trait is small (one method, [`Backend::run`]) so it's trivial to add new
//! backends (e.g., gVisor, Firecracker) without touching the public API.
//!
//! ## Usage
//!
//! ```rust,no_run
//! use forge_sandbox::{Sandbox, SandboxConfig};
//!
//! # async fn example() -> anyhow::Result<()> {
//! let sandbox = Sandbox::for_platform();
//! let config = SandboxConfig::builder()
//!     .command("cargo")
//!     .args(["test", "--no-run"])
//!     .working_dir("/tmp/project")
//!     .build();
//!
//! let output = sandbox.run(&config).await?;
//! println!("stdout: {}", output.stdout);
//! # Ok(())
//! # }
//! ```

#![allow(clippy::needless_return)]

mod backend;
mod config;
mod disabled;
mod linux;
mod macos;
mod windows;

#[cfg(test)]
mod tests;

pub use backend::{Backend, Sandbox};
pub use config::{FilesystemRule, NetworkPolicy, SandboxConfig, SandboxConfigBuilder};

/// Output from a sandboxed process execution.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SandboxOutput {
    /// Captured stdout (UTF-8 lossy)
    pub stdout: String,
    /// Captured stderr (UTF-8 lossy)
    pub stderr: String,
    /// Exit status code
    pub exit_code: i32,
    /// Whether the sandbox was actually enforced (false on `Disabled` backend)
    pub sandboxed: bool,
}

/// Errors that can occur when running a sandboxed command.
#[derive(Debug, thiserror::Error)]
pub enum SandboxError {
    #[error("command not found: {0}")]
    CommandNotFound(String),

    #[error("backend '{0}' is not available on this platform")]
    BackendUnavailable(&'static str),

    #[error("config validation failed: {0}")]
    InvalidConfig(String),

    #[error("sandbox setup failed: {0}")]
    SetupFailed(String),

    #[error("process spawn failed: {0}")]
    SpawnFailed(#[from] std::io::Error),

    #[error("execution timed out after {0:?}")]
    Timeout(std::time::Duration),
}

impl SandboxOutput {
    /// Returns true if the process exited with a non-zero status.
    pub fn failed(&self) -> bool {
        self.exit_code != 0
    }

    /// Returns the combined stdout + stderr output.
    pub fn combined_output(&self) -> String {
        if self.stderr.is_empty() {
            self.stdout.clone()
        } else if self.stdout.is_empty() {
            self.stderr.clone()
        } else {
            format!("{}\n{}", self.stdout, self.stderr)
        }
    }
}
