name: bounty

on:
  issues:
    types: [labeled]
  pull_request_target:
    types: [labeled]

jobs:
  bounty:
    if: contains(github.event.issue.labels.*.name, 'bounty') || contains(github.event.pull_request.labels.*.name, 'bounty')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - uses: actions/checkout@v7
        with:
          ref: ${{ github.head_ref }}
