name: Cargo Deny
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5
      - uses: taiki-e/upload-rust-binary-action@f0d45ae91ee7b8ee928de7a9d04d893a08bcbec6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tool: cargo-deny
      - name: Check
        run: cargo deny check --log-level error
