name: Cargo Deny
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cargo-deny:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4@11bd71901bbe5b1630ceea73d27597364c9af683
      - uses: taiki-e/upload-rust-binary-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tool: cargo-deny
      - name: Check
        run: cargo deny check --log-level error
