name: release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write
  packages: write

jobs:
  release:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, x86_64-unknown-linux-musl, aarch64-unknown-linux-musl, x86_64-apple-darwin, aarch64-apple-darwin, x86_64-pc-windows-msvc]
    steps:
      - uses: actions/checkout@v7
      - uses: arduino/setup-protoc@v3
      - uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - uses: ClementTsang/cargo-action@v0.0.7
        with:
          command: build
          args: --target ${{ matrix.target }} --release
      - uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: target/${{ matrix.target }}/release/forgecode*
          tag_name: ${{ github.ref_name }}
          replace: true
      - uses: actions/checkout@v7
      - run: cargo publish --all-features
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
